In [1]:
import sys
sys.path.append("../")

from config import load_config
from train import Trainer

import numpy as np
import matplotlib.pyplot as plt
from config import FilterConfig, DataConfig
from nn.net import Net, ResNet, NetConfig

import torch

c:\Users\luk\miniconda3\envs\ml\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
data_cfg = DataConfig(
    path="C:/Users/luk/Desktop/kyselica/classification_of_light_curves/resources/Fall_2021_2",
    labels=["cz-3", "titan", "falcon_9", "atlas_5"])

filter_cfg = FilterConfig(
    n_bins=30,
    n_gaps=2, 
    gap_size=0, 
    rms_ratio= 0,
    non_zero_ratio=0.2
)
net_cfg = NetConfig(
  name = "4ClassesS",
  checkpoint = None,
  input_size = 300,
  n_channels = 10,
  n_classes = 4,
  hid_dim = 128,
  stride = 2,
  kernel_size = 5
)

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
net = ResNet(net_cfg.n_classes, device=device, name="4Classes_No_Sampler")


cuda:0


In [4]:

net = Net(net_cfg)
trainer = Trainer(net, net_cfg=net_cfg, data_cfg=data_cfg, filter_cfg=filter_cfg)
print(len(trainer.data))

Folder C:/Users/luk/Desktop/kyselica/classification_of_light_curves/resources/Fall_2021_2: 100%|██████████| 495/495 [00:00<00:00, 691.15it/s]


label: cz-3 -> 19085 examples
label: titan -> 2379 examples
label: falcon_9 -> 1768 examples
label: atlas_5 -> 8004 examples
4


In [10]:
trainer.train(30, print_on=True, save_interval=10, tensorboard_on=False)

Epoch 1: 100%|██████████| 489/489 [00:01<00:00, 390.00it/s]

Train:
	Loss: 0.005094581804023231
	Acc: 87.19106159559482


Validation:
	Loss: 0.01111511436383931
	Acc: 72.01729106628243


Epoch 2: 100%|██████████| 489/489 [00:01<00:00, 396.67it/s]

Train:
	Loss: 0.004976758585212929
	Acc: 87.59124087591242
Validation:
	Loss: 0.009943901213689179
	Acc: 77.57925072046109



Epoch 3: 100%|██████████| 489/489 [00:01<00:00, 399.28it/s]

Train:
	Loss: 0.00486021461667188
	Acc: 88.06825457805097
Validation:
	Loss: 0.01103297846082396
	Acc: 72.36311239193084



Epoch 4: 100%|██████████| 489/489 [00:01<00:00, 395.60it/s]

Train:
	Loss: 0.004936989858242206
	Acc: 87.77052119349469
Validation:
	Loss: 0.011223370398039282
	Acc: 72.27665706051873



Epoch 5: 100%|██████████| 489/489 [00:01<00:00, 393.14it/s]

Train:
	Loss: 0.004671038759836565
	Acc: 88.44282238442823
Validation:
	Loss: 0.010549857224059194
	Acc: 74.14985590778097



Epoch 6: 100%|██████████| 489/489 [00:01<00:00, 393.22it/s]

Train:
	Loss: 0.0048513250717811375
	Acc: 87.82494557561787
Validation:
	Loss: 0.011211205522643833
	Acc: 73.14121037463977



Epoch 7: 100%|██████████| 489/489 [00:01<00:00, 397.79it/s]

Train:
	Loss: 0.004591583008497523
	Acc: 88.61890126776795
Validation:
	Loss: 0.011439665253817618
	Acc: 73.86167146974063



Epoch 8: 100%|██████████| 489/489 [00:01<00:00, 377.52it/s]

Train:
	Loss: 0.004540743399419758
	Acc: 88.80138301959278


Validation:
	Loss: 0.01065936754493106
	Acc: 74.0922190201729


Epoch 9: 100%|██████████| 489/489 [00:01<00:00, 339.81it/s]

Train:
	Loss: 0.004495937300921659
	Acc: 88.86861313868614
Validation:
	Loss: 0.011465563812998103
	Acc: 72.59365994236312



Epoch 10: 100%|██████████| 489/489 [00:01<00:00, 343.51it/s]

Train:
	Loss: 0.004543889284667651
	Acc: 88.69573568958894
Validation:
	Loss: 0.011105995236627971
	Acc: 74.20749279538904



Epoch 11: 100%|██████████| 489/489 [00:01<00:00, 333.65it/s]

Train:
	Loss: 0.004434446814655914
	Acc: 89.05109489051095
Validation:
	Loss: 0.011379069605209544
	Acc: 73.37175792507205



Epoch 12: 100%|██████████| 489/489 [00:01<00:00, 338.78it/s]

Train:
	Loss: 0.004303809814041296
	Acc: 89.27199385324626


Validation:
	Loss: 0.01130916617232834
	Acc: 75.01440922190201


Epoch 13: 100%|██████████| 489/489 [00:01<00:00, 343.61it/s]

Train:
	Loss: 0.004313735308418342
	Acc: 89.41925982840311
Validation:
	Loss: 0.0103784150120863
	Acc: 76.59942363112393



Epoch 14: 100%|██████████| 489/489 [00:01<00:00, 341.21it/s]

Train:
	Loss: 0.004265408511350723
	Acc: 89.51530285567935
Validation:
	Loss: 0.011665372788999455
	Acc: 73.37175792507205



Epoch 15: 100%|██████████| 489/489 [00:01<00:00, 342.39it/s]

Train:
	Loss: 0.004304469732454359
	Acc: 89.4096555256755
Validation:
	Loss: 0.010858486722206781
	Acc: 75.12968299711815



Epoch 16: 100%|██████████| 489/489 [00:01<00:00, 342.31it/s]

Train:
	Loss: 0.004128738748255083
	Acc: 89.95069791266488
Validation:
	Loss: 0.011215176571073085
	Acc: 76.22478386167147



Epoch 17: 100%|██████████| 489/489 [00:01<00:00, 341.04it/s]

Train:
	Loss: 0.004235414263158374
	Acc: 89.38084261749265
Validation:
	Loss: 0.011857965990408443
	Acc: 73.17002881844381



Epoch 18: 100%|██████████| 489/489 [00:01<00:00, 337.04it/s]

Train:
	Loss: 0.003989123677664049
	Acc: 89.92828787296709
Validation:
	Loss: 0.010875951912229695
	Acc: 76.54178674351586



Epoch 19: 100%|██████████| 489/489 [00:01<00:00, 344.09it/s]

Train:
	Loss: 0.004083015530863555
	Acc: 89.8738634908439
Validation:
	Loss: 0.012644481778669519
	Acc: 71.98847262247838



Epoch 20: 100%|██████████| 489/489 [00:01<00:00, 339.92it/s]

Train:
	Loss: 0.004055036891873689
	Acc: 89.95389934690742
Validation:
	Loss: 0.011118646467744317
	Acc: 76.36887608069165



Epoch 21: 100%|██████████| 489/489 [00:01<00:00, 334.42it/s]

Train:
	Loss: 0.003917048416854916
	Acc: 90.39249583813549
Validation:
	Loss: 0.011603039822758846
	Acc: 74.75504322766571



Epoch 22: 100%|██████████| 489/489 [00:01<00:00, 341.91it/s]

Train:
	Loss: 0.003930102146912187
	Acc: 90.39889870662057
Validation:
	Loss: 0.011205062484671903
	Acc: 76.54178674351586



Epoch 23: 100%|██████████| 489/489 [00:01<00:00, 337.43it/s]

Train:
	Loss: 0.003975557096353093
	Acc: 90.28044563964657


Validation:
	Loss: 0.012100296106198826
	Acc: 76.22478386167147


Epoch 24: 100%|██████████| 489/489 [00:01<00:00, 339.37it/s]

Train:
	Loss: 0.003849836045165544
	Acc: 90.45332308874376
Validation:
	Loss: 0.011535069003848708
	Acc: 75.61959654178675



Epoch 25: 100%|██████████| 489/489 [00:01<00:00, 332.53it/s]

Train:
	Loss: 0.003898593745029934
	Acc: 90.36368292995262


Validation:
	Loss: 0.011499294897374753
	Acc: 75.38904899135447


Epoch 26: 100%|██████████| 489/489 [00:01<00:00, 341.57it/s]

Train:
	Loss: 0.003857009847505503
	Acc: 90.32846715328468
Validation:
	Loss: 0.011909921861554816
	Acc: 74.20749279538904



Epoch 27: 100%|██████████| 489/489 [00:01<00:00, 329.73it/s]

Train:
	Loss: 0.0037050224744102577
	Acc: 91.01677551543091


Validation:
	Loss: 0.012066200679919812
	Acc: 75.24495677233429


Epoch 28: 100%|██████████| 489/489 [00:01<00:00, 338.53it/s]

Train:
	Loss: 0.0036488493834728655
	Acc: 90.82148802663593
Validation:
	Loss: 0.01152247038957242
	Acc: 76.74351585014409



Epoch 29: 100%|██████████| 489/489 [00:01<00:00, 339.76it/s]

Train:
	Loss: 0.0038124214974564483
	Acc: 90.5749775899603
Validation:
	Loss: 0.011538902298491104
	Acc: 76.28242074927954



Epoch 30: 100%|██████████| 489/489 [00:01<00:00, 337.59it/s]

Train:
	Loss: 0.003656012471808535
	Acc: 91.24727878089384


Validation:
	Loss: 0.011545083495434776
	Acc: 76.71469740634005


In [12]:
trainer.evaluate(data_cfg.labels)

0 cz-3
1 titan
2 falcon_9
3 atlas_5
Train:
	Loss: 0.003987497735735166
	Acc: 90.09796388782175
Validation:
	Loss: 0.011633343760256239
	Acc: 76.54178674351586
[[1694   46  210  162]
 [  19  215    4   21]
 [  85    1  104   16]
 [ 166   57   27  643]]
Precision:
 [80.20833333333334, 83.01158301158301, 50.48543689320388, 72.00447928331467]
Recall:
 [86.25254582484725, 67.39811912225704, 30.144927536231886, 76.36579572446556]


In [7]:
data_cfg.labels

['cz-3', 'titan', 'falcon_9', 'atlas_5']

In [8]:
import torch.nn as nn
import torch

data_loader = trainer.val_loader

criterion = nn.NLLLoss()

total_loss = 0
total = 0
correct = 0

i = 0
with torch.no_grad():   
    for data in data_loader:
        inputs, labels = data
        labels = labels.long()
        
        inputs = inputs.reshape(-1,1,300).double()
        outputs = net(inputs)
        _, predicted = torch.max(outputs.data, 1)

        loss = criterion(outputs, labels)
        total_loss += loss.item()
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        i += 1
        if i == 2:
            break





In [9]:
ok_falcon = np.logical_and(labels == 0, predicted == 1)
falcon = inputs[ok_falcon][1][0].numpy()

C:\Users\luk\AppData\Local\Temp\ipykernel_15288\224874507.py:2: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (Triggered internally at  C:\cb\pytorch_1000000000000\work\aten\src\ATen/native/IndexingUtils.h:28.)
  falcon = inputs[ok_falcon][1][0].numpy()


IndexError: index 1 is out of bounds for dimension 0 with size 0

In [ ]:
import matplotlib.pyplot as plt

atlas = falcon
plt.scatter(np.linspace(0,1, 300)[atlas != -1], atlas[atlas != -1])

In [ ]:
[atlas != -1]