In [1]:
import sys
sys.path.append("../")

from config import load_config
from train import Trainer

import numpy as np
import matplotlib.pyplot as plt
from config import FilterConfig
from nn.net import Net, ResNet

In [2]:
data_cfg, net_cfg, filter_cfg = load_config()

In [3]:
filter_cfg = FilterConfig(
    n_bins=15,
    n_gaps=4, 
    gap_size=2, 
    non_zero_ratio=0.2
)

In [4]:

# net = Net(net_cfg)
net = ResNet(net_cfg.n_classes)
trainer = Trainer(net, net_cfg=net_cfg, data_cfg=data_cfg, filter_cfg=filter_cfg)
print(len(trainer.data))

Folder c:/Users/danok/work/dizertacka/system/resources/Fall_2021_2: 100%|██████████| 495/495 [00:00<00:00, 1090.75it/s]


3


In [24]:
trainer.train(30, print_on=False)

Epoch 30: 100%|██████████| 220/220 [00:09<00:00, 24.33it/s]


In [26]:
trainer.evaluate(data_cfg.labels)

0 falcon_9
1 atlas_5
2 delta_4
Train:
	Loss: 0.004152341784790506
	Acc: 88.66060002843737
Validation:
	Loss: 0.008025802286507134
	Acc: 82.0742637644046
[[ 230   97   16]
 [  87 1032   15]
 [  35   30   20]]
Precision:
 [67.05539358600583, 91.005291005291, 23.52941176470588]
Recall:
 [65.3409090909091, 89.04227782571182, 39.21568627450981]


In [6]:
data_cfg.labels

['falcon_9', 'atlas_5', 'delta_4']

In [7]:
import pandas as pd

In [9]:
cm = [[110,  75,  14],
 [ 21, 882,  12],
 [  3,  13,  15]]
data = []
for l, d in zip(data_cfg.labels, cm):
    data.append([l]+d)

In [10]:
data

[['falcon_9', 110, 75, 14], ['atlas_5', 21, 882, 12], ['delta_4', 3, 13, 15]]

In [17]:
df = pd.DataFrame(data, columns=["label"] + data_cfg.labels)

In [13]:
df

label  falcon_9  atlas_5  delta_4
0  falcon_9       110       75       14
1   atlas_5        21      882       12
2   delta_4         3       13       15

In [8]:
data_cfg.labels

['falcon_9', 'atlas_5', 'delta_4']