In [2]:
import numpy as np 
import torch

c:\Users\Kyselica\Documents\programs\anaconda\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
torch.randint(1,10,(3,))

tensor([4, 1, 8])

In [4]:
a = np.random.rand(3,10)

In [12]:
np.roll(a, 1)

array([[0.42066101, 0.75802239, 0.67171369, 0.48019037, 0.19548299,
        0.87508209, 0.91543505, 0.65857229, 0.06913325, 0.53446638],
       [0.64296394, 0.83754449, 0.16340354, 0.54102739, 0.30881208,
        0.53937789, 0.09519797, 0.58994808, 0.02935054, 0.70848702],
       [0.56570425, 0.32406663, 0.16307638, 0.53257037, 0.25070819,
        0.93495689, 0.90277262, 0.93430676, 0.00742596, 0.74050573]])

In [14]:
list(a)

[array([0.75802239, 0.67171369, 0.48019037, 0.19548299, 0.87508209,
        0.91543505, 0.65857229, 0.06913325, 0.53446638, 0.64296394]),
 array([0.83754449, 0.16340354, 0.54102739, 0.30881208, 0.53937789,
        0.09519797, 0.58994808, 0.02935054, 0.70848702, 0.56570425]),
 array([0.32406663, 0.16307638, 0.53257037, 0.25070819, 0.93495689,
        0.90277262, 0.93430676, 0.00742596, 0.74050573, 0.42066101])]