In [1]:
import json

In [2]:
PATH = "../../resources/SDLCD/DATA.json"
PATH_database = "../../resources/SDLCD/database.json"

In [6]:
with open(PATH, 'r') as f:
    data = json.load(f)
    
with open(PATH_database, 'r') as f:
    database = json.load(f)

In [7]:
name_database = {}

In [8]:
database['1']['object-id']

for k in database:
    name_database[database[k]['object-id']] = database[k].get('object-name', '') 

In [9]:
database['1']["object-name"]

'SL-12 R/B(2)'

In [10]:
print(name_database)

{'00011B': 'SL-12 R/B(2)', '00049A': 'RADUGA 1-5', '00051D': 'SL-12 R/B(2)', '00082A': 'CHINASAT 31 (BEIDOU 1B)', '01014A': 'EKRAN 21', '01031A': 'GOES 12', '01037A': 'COSMOS 2379', '01037D': 'SL-12 R/B(2)', '02003C': 'H-2A R/B', '02051B': 'DELTA 4 R/B', '02062B': 'BREEZE-M R/B', '03007B': 'ARIANE 44L R/B', '03024A': 'AMC-9 (GE-12)', '03028C': 'ARIANE 5 R/B', '04010A': 'RADUGA 1-7', '04015D': 'SL-12 R/B(2)', '05046C': 'ARIANE 5 R/B', '06012B': 'ATLAS 5 CENTAUR R/B', '06022D': 'SL-12 R/B(2)', '06023B': 'BLOCK DM-SL R/B', '06034B': 'BLOCK DM-SL R/B', '08013B': 'BLOCK DM-SL R/B', '08022B': 'SL-23 R/B', '08065C': 'ARIANE 5 DEB (SYLDA)', '09033B': 'DELTA 4 R/B', '09042B': 'BREEZE-M R/B', '10061B': 'BREEZE-M R/B', '11001B': 'FREGAT R/B', '11016C': 'ARIANE 5 R/B', '11022C': 'ARIANE 5 R/B', '12012D': 'SL-12 R/B(2)', '12035C': 'ARIANE 5 R/B', '13077B': 'BREEZE-M R/B', '14011C': 'ARIANE 5 R/B', '14046B': 'FALCON 9 R/B', '14064B': 'BREEZE-M R/B', '14085A': 'DUMMY SAT 2/BREEZE-M', '15048B': 'BLOCK

In [11]:
list(data[0].keys())[0]

'16037B'

In [12]:
for d in data:
    k = list(d.keys())[0]
    d[k]['object-name'] = name_database.get(k, '')

In [13]:
for k in name_database:
    if 'R/B' in name_database[k]:
        print(k, name_database[k])

00011B SL-12 R/B(2)
00051D SL-12 R/B(2)
01037D SL-12 R/B(2)
02003C H-2A R/B
02051B DELTA 4 R/B
02062B BREEZE-M R/B
03007B ARIANE 44L R/B
03028C ARIANE 5 R/B
04015D SL-12 R/B(2)
05046C ARIANE 5 R/B
06012B ATLAS 5 CENTAUR R/B
06022D SL-12 R/B(2)
06023B BLOCK DM-SL R/B
06034B BLOCK DM-SL R/B
08013B BLOCK DM-SL R/B
08022B SL-23 R/B
09033B DELTA 4 R/B
09042B BREEZE-M R/B
10061B BREEZE-M R/B
11001B FREGAT R/B
11016C ARIANE 5 R/B
11022C ARIANE 5 R/B
12012D SL-12 R/B(2)
12035C ARIANE 5 R/B
13077B BREEZE-M R/B
14011C ARIANE 5 R/B
14046B FALCON 9 R/B
14064B BREEZE-M R/B
15048B BLOCK DM-SL R/B
16065C YZ-2 R/B
16071B ATLAS 5 CENTAUR R/B
16080B EPSILON R/B
17017B FALCON 9 R/B
17046C BREEZE-M R/B
17048B H-2A R/B
17063B FALCON 9 R/B
17086B FREGAT R/B
67066G TITAN 3C TRANSTAGE R/B
68050J TITAN 3C TRANSTAGE R/B
71006B ATLAS CENTAUR R/B
74039C TITAN 3C TRANSTAGE R/B
74060F SL-12 R/B(2)
75036D SL-6 R/B(2)
75063D SL-6 R/B(2)
75081D SL-6 R/B(2)
75091B ATLAS CENTAUR R/B
76073B ATLAS CENTAUR R/B
77021D SL-6 

In [14]:
names = [name_database.get(list(d.keys())[0], "None") for d in data]

In [15]:
names_rb = [name_database.get(list(d.keys())[0], "None").split()[0] for d in data if 'R/B' in name_database.get(list(d.keys())[0], "None")]

In [4]:
import numpy as np

In [25]:
labels = ["cz_3", "falcon_9", "atlas",  "h2a", "globalstar"]
regexes=[r'CZ-3B.*', r'FALCON 9.*', r'ATLAS [5|V] CENTAUR',  r'H-2A.*', r'GLOBALSTAR.*']

In [38]:
for n in names:
    if re.search(regexes[4], n) is not None:
        print(n)

In [5]:
import re

repr(re.search(r'(\d+)', "ATLAS "))

'None'

In [39]:
name_database

{'00011B': 'SL-12 R/B(2)',
 '00049A': 'RADUGA 1-5',
 '00051D': 'SL-12 R/B(2)',
 '00082A': 'CHINASAT 31 (BEIDOU 1B)',
 '01014A': 'EKRAN 21',
 '01031A': 'GOES 12',
 '01037A': 'COSMOS 2379',
 '01037D': 'SL-12 R/B(2)',
 '02003C': 'H-2A R/B',
 '02051B': 'DELTA 4 R/B',
 '02062B': 'BREEZE-M R/B',
 '03007B': 'ARIANE 44L R/B',
 '03024A': 'AMC-9 (GE-12)',
 '03028C': 'ARIANE 5 R/B',
 '04010A': 'RADUGA 1-7',
 '04015D': 'SL-12 R/B(2)',
 '05046C': 'ARIANE 5 R/B',
 '06012B': 'ATLAS 5 CENTAUR R/B',
 '06022D': 'SL-12 R/B(2)',
 '06023B': 'BLOCK DM-SL R/B',
 '06034B': 'BLOCK DM-SL R/B',
 '08013B': 'BLOCK DM-SL R/B',
 '08022B': 'SL-23 R/B',
 '08065C': 'ARIANE 5 DEB (SYLDA)',
 '09033B': 'DELTA 4 R/B',
 '09042B': 'BREEZE-M R/B',
 '10061B': 'BREEZE-M R/B',
 '11001B': 'FREGAT R/B',
 '11016C': 'ARIANE 5 R/B',
 '11022C': 'ARIANE 5 R/B',
 '12012D': 'SL-12 R/B(2)',
 '12035C': 'ARIANE 5 R/B',
 '13077B': 'BREEZE-M R/B',
 '14011C': 'ARIANE 5 R/B',
 '14046B': 'FALCON 9 R/B',
 '14064B': 'BREEZE-M R/B',
 '14085A': 'DUM

In [22]:
from collections import defaultdict

def load_SDLCD_data(PATH, PATH_database, labels, regexes):
    with open(PATH, 'r') as f:
        data = json.load(f)
    
    with open(PATH_database, 'r') as f:
        database = json.load(f)

    name_database = {}

    for k in database:
        object_id = database[k]['object-id']
        object_name = database[k].get('object-name', '')
        name_database[object_id] = object_name
    
    
    labeled_data = {l: [] for l in labels}

    for d in data:
        object_id = list(d.keys())[0]
        object_name = name_database.get(object_id, '')

        if object_name == '':
            continue
        
        array = np.array([d[object_id][char + str(number)] for char in "ab" for number in range(1, 9)])

        for i, l in enumerate(labels):
            if re.search(regexes[i], object_name) is not None:
                labeled_data[l].append(array)
                break
        
    return labeled_data

In [26]:
labeled_data = load_SDLCD_data(PATH, PATH_database, labels, regexes)

In [27]:
labeled_data

{'cz_3': [array([-0.08134541, -0.03325909, -0.13136846, -0.04162199, -0.00965847,
         -0.01853292,  0.00299906,  0.00060776,  0.00770873, -0.00642452,
         -0.01176785,  0.00762302, -0.00424449, -0.00134893, -0.00309872,
          0.00162564]),
  array([-0.29886156,  0.04404254,  1.01619881,  0.04240369, -0.19510087,
         -0.00718653, -0.02470657,  0.00798448, -0.14953613, -0.02805591,
         -0.22086777, -0.02038317, -0.10031876, -0.02221997, -0.27135751,
         -0.05273968]),
  array([-0.00246525,  0.02658295, -1.46975487,  0.60413643, -0.02942005,
         -0.00443724, -0.05837368, -0.41305508,  0.00474614, -0.05990328,
          0.1989936 ,  0.04176003,  0.02455216,  0.03231411, -0.0583423 ,
          0.09334657]),
  array([-1.88080986e-02,  3.84483433e-02, -7.56309645e-01,  8.96159191e-02,
          1.34352103e-02, -2.65836341e-02,  1.91982853e-02,  1.17600682e-01,
         -6.27177584e-03, -3.66650990e-02,  1.58608468e-02, -1.81526045e-02,
          7.37497115e-0

In [28]:
y = []

for i, l in enumerate(labels):
    y += [i] * len(labeled_data[l])

In [33]:
x = []
y = []
for l, k in labeled_data.items():
    x += k
    y += [labels.index(l)] * len(k)

x = np.array(x)
y = np.array(y)
print(x.shape)
print(y.shape)
    

(323, 16)
(323,)


In [34]:
path_original_data = "/home/daniel/Documents/work/classification_of_light_curves/output/datasets/Experiments/FourierDatasetfourier_True_std_False_residuals_False_rms_False_amplitude_False_lc_False_reconstructed_lc_False_push_to_max_True_10000"

In [36]:
np.load(path_original_data + "/train_y.npy").shape

(19765,)

In [3]:
import os

In [38]:
os.makedirs('/home/daniel/Documents/work/classification_of_light_curves/output/datasets/SDLCD', exist_ok=True)

In [5]:
save_path = "/home/daniel/Documents/work/classification_of_light_curves/output/datasets/SDLCD"

In [41]:
np.save(save_path + "/test_y.npy", y)
np.save(save_path + "/test_x.npy", x)

In [4]:
import numpy as np

In [6]:
X = np.load(save_path + "/test_x.npy")
y = np.load(save_path + "/test_y.npy")

In [11]:
cut = 3
tmp = y.tolist()
train_indices = {}
val_indices = {}
for i in set(tmp):
    print(i, tmp.count(i)//3)
    indices = list(range(tmp.count(i)))
    train_indices[i] = indices[:tmp.count(i)//3]
    val_indices[i] = indices[tmp.count(i)//3:]

0 41
1 34
2 23
3 8


In [13]:
X_train = []
X_val = []
y_train = []
y_val = []
for i in train_indices:
    d = X[y == i]
    d_train = d[train_indices[i]]
    d_val = d[val_indices[i]]
    X_train += d_train.tolist()
    X_val += d_val.tolist()
    y_train += [i] * len(d_train)
    y_val += [i] * len(d_val)
    print(i, len(test_indices[i]), len(val_indices[i]))

0 41 83
1 34 70
2 23 48
3 8 16


In [14]:
X_train = np.array(X_train)
X_val = np.array(X_val)
y_train = np.array(y_train)
y_val = np.array(y_val)

print(X_train.shape)
print(X_val.shape)
print(y_train.shape)
print(y_val.shape)

(106, 16)
(217, 16)
(106,)
(217,)


In [15]:
np.save(save_path + "/train_x.npy", X_train)
np.save(save_path + "/train_y.npy", y_train)
np.save(save_path + "/val_x.npy", X_val)
np.save(save_path + "/val_y.npy", y_val)